### ISSUE TITLE
Email notifications query

### ISSUE THREAD

**Issue by SeanDurban** [dwyerse/EventPlanner#10]
Do we know at this point what email service the customer is expecting to send their emails through? The implementation will be different for different mailing services (Gmail vs outlook etc) therefore we need some indication of which one to go forward with.

Or would this be a case similar to the payment system?

**Comment by andrewbutterfield** [comment]
Similar to the payment system, I guess.
Pick whatever seems simplest - can't you do smtp calls from unix directly?
