### ISSUE TITLE
Feature Dependencies

### ISSUE THREAD

**Issue by SeanDurban** [dwyerse/EventPlanner#4]
Just a question on how the dependencies between features should be handled:

If a feature requires another feature to be implemented first, should we assume that feature has been implemented when estimating? Or should we add our estimate for the dependencies to our estimate for this feature?

For example)  "I want to be able to see the rsvp list" 
This would assume many other features have been implemented: 

- Invite people to event  (Admin)
  - Create an event
    - Login to admin account
      - Ability to create an admin account
- Ability to RSVP to event (Attendee)
  - View event
  - Login to attendee account
    -Create attendee account

This example may not be the best but nearly all features have similar dependencies. But they're not straight forward to group either. As then we end up with a small number of independent feature groups or maybe even a single one. Since many strip back to being able to create an account, login etc

**Comment by andrewbutterfield** [comment]
if feature a depends on feature b, both ink the backlog, then estimate for feature b as standalone,
and estimate for a assuming that b has been built. But you make sure that if a is on the backlog, then so must b be, and of higher priority, by pointing out the issue to the customer.

The dependencies above are all real, and so will determine implementation order
